# Generated by Django 5.0.6 on 2024-05-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conid', models.CharField(max_length=64, verbose_name='Contract Id')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('CLÉMENCE', 'CLÉMENCE'), ('CLEMENTINE', 'CLEMENTINE')], default='CLÉMENCE', max_length=64, verbose_name='Strategy')),
                ('trade_id', models.CharField(db_index=True, default=None, editable=False, max_length=64, null=True, verbose_name='Reference ID')),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('REJECTED', 'REJECTED')], default='OPEN', max_length=64, verbose_name='Status')),
                ('open_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('profit_loss', models.FloatField(blank=True, null=True)),
                ('sold_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conid', models.CharField(db_index=True, max_length=64, verbose_name='Contract Id')),
                ('update_time', models.DateTimeField()),
                ('last', models.FloatField()),
                ('bid', models.FloatField(null=True)),
                ('ask', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Prices',
                'unique_together': {('conid', 'update_time')},
            },
        ),
    ]
