# Generated by Django 5.0.6 on 2024-05-30 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0001_initial')
    ]

    operations = [
        migrations.RunSQL(
            """
                CREATE SEQUENCE order_number
                START WITH 1
                INCREMENT BY 1
                NO MINVALUE
                NO MAXVALUE
                CACHE 1;
                """
        ),
    ]
