# Generated by Django 5.0.6 on 2024-06-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_number_sequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='limit_percentage',
            new_name='limit_factor',
        ),
        migrations.RenameField(
            model_name='strategy',
            old_name='stop_percentage',
            new_name='stop_factor',
        ),
    ]
