# Generated by Django 5.0.6 on 2024-06-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_limit_percentage_strategy_limit_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ccp_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
