# Generated by Django 5.0.6 on 2024-06-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_ccp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='precision',
            field=models.IntegerField(default=5),
        ),
    ]
